### ISSUE TITLE
Console fails to start in GCP k8s

### ISSUE THREAD

**Issue by walkingbrad** [pluralsh/plural#626]
## Summary
I initialize, build, and deploy plural to GCP "successfully", but the `console` fails to start up as seen in GCP -> Kubernetes ->> Workloads. Visiting its url shows a standard nginx 503 error. I've wiped my local `context.yaml` and started the `plural` setup process from scratch from `plural init`, but I still get the same result.

<img width="591" alt="Screen Shot 2022-10-19 at 5 31 14 PM" src="https://user-images.githubusercontent.com/5247616/196829314-62546587-d35e-4472-b479-9252dce3368b.png">

Here are the errors in GCP, which mean nothing to me:

<img width="2009" alt="Screen Shot 2022-10-19 at 5 25 20 PM" src="https://user-images.githubusercontent.com/5247616/196829071-502a28fd-78da-4457-af66-041ccd511555.png">

My other bundle, Jitsu, seemed to be working initially when accessing its dedicated url, but now it shows:

<img width="434" alt="Screen Shot 2022-10-19 at 5 56 57 PM" src="https://user-images.githubusercontent.com/5247616/196831691-e7fe0d51-cfc4-4f17-9c3b-e2afd91efb5e.png">

## Reproduction
Set up gcloud cli using my personal account as application-default login

**Set up GCP project**
1. Create new project
2. [Enable the Kubernetes Engine API](https://cloud.google.com/kubernetes-engine/docs/quickstart)
3. [Enable the Google DNS API](https://excelnotes.com/enable-cloud-dns-api/)
4. Also enable a few other APIs that are not documented but that the `plural` cli notifies us we need to enable when deploying for the first time

**Set up Plural**
1. `plural init` (using the google provider)
3. `plural bundle install console console-gcp`
5. `plural bundle install jitsu jitsu-gcp`
6. `plural build`
7. `plural deploy --commit "something"`
8. Check GCP K8s Workloads to see what's up-and-running. 

Expected: all workloads to be green
Received: the `console` workload is red

## Plural UI/UX Issue Screenshots
N/A

## Additional Info about Your Environment
**`context.yaml`**
```
apiVersion: plural.sh/v1alpha1
kind: Context
spec:
  bundles:
  - repository: console
    name: console-gcp
  - repository: jitsu
    name: jitsu-gcp
  buckets:
  - h3x-plural-postgres-wal
  domains:
  - console.h3x.onplural.sh
  - redis.h3x.onplural.sh
  - redis2.h3x.onplural.sh
  - jitsu.h3x.onplural.sh
  - api.jitsu.h3x.onplural.sh
  configuration:
    bootstrap:
      vpc_name: plural
    console:
      admin_name: Admin
      console_dns: console.h3x.onplural.sh
      git_email: brad@h3x.app
      git_user: walkingbrad
      passphrase: ""
      private_key: REDACTED
      public_key: REDACTED
      repo_url: git@github.com:h3x-app/plural.git
    ingress-nginx: {}
    jitsu:
      apiHostname: api.jitsu.h3x.onplural.sh
      hostname: jitsu.h3x.onplural.sh
    monitoring: {}
    postgres:
      wal_bucket: h3x-plural-postgres-wal
    redis:
      masterHostname: redis.h3x.onplural.sh
      replicaHostname: redis2.h3x.onplural.sh
```

APIs on the GCP project (note that Compute Engine has 5 errors)
<img width="521" alt="Screen Shot 2022-10-19 at 6 19 28 PM" src="https://user-images.githubusercontent.com/5247616/196833866-bc85240b-881e-46ff-9490-55c299b717c2.png">

Compute engine errors:
<img width="675" alt="Screen Shot 2022-10-19 at 6 18 49 PM" src="https://user-images.githubusercontent.com/5247616/196833923-01dd1869-cd50-449d-bcd9-1ecbe8893fef.png">

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
