### ISSUE TITLE
Console login with OIDC fails b/c of bad redirect_uri

### ISSUE THREAD

**Issue by walkingbrad** [pluralsh/plural#636]
## Summary
After deploying Plural Console to my own k8s engine on GCP, clicking "Login with Plural" fails with an OAuth error presumably b/c it doesn't like the `redirect_uri`. 

I enabled OIDC during the `plural bundle install console console-gcp` step, however I can't seem to notice that decision affecting any of the local files in the repo. If I run through the whole setup process again and choose against OIDC, my local files still look the same as when I chose to use OIDC, so idk where that setting is stored.

It seems that my domain may not be pre-registered in Plural's own OAuth config?

Clicking the login button goes to this url:
https://oidc.plural.sh/oauth2/auth?client_id=bbe5c802-f60d-4612-b4d4-32ad286a1bcd&redirect_uri=https%3A%2F%2Fconsole.h3x.onplural.sh%2Foauth%2Fcallback&response_type=code&scope=openid&state=ASC4AfQt_wH3JTNx4ygFvWgQrc8l-hL-Q3Jsd-p6wts%3D

Which then redirects to this url:
https://oidc.plural.sh/oauth2/fallbacks/error?error=invalid_request&error_description=The+request+is+missing+a+required+parameter%2C+includes+an+invalid+parameter+value%2C+includes+a+parameter+more+than+once%2C+or+is+otherwise+malformed&error_hint=The+%22redirect_uri%22+parameter+does+not+match+any+of+the+OAuth+2.0+Client%27s+pre-registered+redirect+urls.

## Reproduction
1. `plural init` (using the google provider)
3. `plural bundle install console console-gcp`
5. `plural bundle install jitsu jitsu-gcp` (probably unrelated)
6. `plural build`
7. `plural deploy --commit "something"`
8. Open https://console.h3x.onplural.sh
9. Click "Login with Plural"

Expected: some kind of login screen
Received: oauth error

## Plural UI/UX Issue Screenshots
<img width="536" alt="Screen Shot 2022-10-24 at 1 24 45 PM" src="https://user-images.githubusercontent.com/5247616/197592294-b946eb4e-3370-490e-a37e-6a6ca18c9d0d.png">

<img width="1089" alt="Screen Shot 2022-10-24 at 1 24 37 PM" src="https://user-images.githubusercontent.com/5247616/197592300-93d56f6e-3753-4a38-8867-e7739ef8103d.png">

## Additional Info about Your Environment
**`context.yaml`**
```
apiVersion: plural.sh/v1alpha1
kind: Context
spec:
  bundles:
  - repository: console
    name: console-gcp
  - repository: jitsu
    name: jitsu-gcp
  buckets:
  - h3x-plural-postgres-wal
  domains:
  - console.h3x.onplural.sh
  - redis.h3x.onplural.sh
  - redis2.h3x.onplural.sh
  - jitsu.h3x.onplural.sh
  - api.jitsu.h3x.onplural.sh
  configuration:
    bootstrap:
      vpc_name: plural
    console:
      admin_name: Admin
      console_dns: console.h3x.onplural.sh
      git_email: brad@h3x.app
      git_user: walkingbrad
      passphrase: REDACTED
      private_key: REDACTED
      public_key: REDACTED
      repo_url: git@github.com:h3x-app/plural.git
    ingress-nginx: {}
    jitsu:
      apiHostname: api.jitsu.h3x.onplural.sh
      hostname: jitsu.h3x.onplural.sh
    monitoring: {}
    postgres:
      wal_bucket: h3x-plural-postgres-wal
    redis:
      masterHostname: redis.h3x.onplural.sh
      replicaHostname: redis2.h3x.onplural.sh
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
